MVCWFE/Controllers/Customer1Controller.cs
using System.Web.Mvc;
using MVCWFE.ServiceReference1;

namespace MVCWFE.Controllers
{
    public class Customer1Controller : Controller
    {
      WebService1SoapClient client = new WebService1SoapClient();

        // View all Customers

        [HttpGet]
        public ActionResult Index()
        {
             return View(client.customerList());  
        }

        // View Order details of a particular customer 

        public ActionResult OrderDetails(string id)
        {
            return View(client.OrderDetails(id));
        }

        // View details of Customers
            public ActionResult Details(string id)
        {
            return View(client.CustomerDetail(id));
        }

        // Create Customer
        public ActionResult Create()
        {
            return View(new Customer1());
        }
              
        [HttpPost]
        public ActionResult Create(Customer1 customer)
        {
            int create = client.createCustomer(customer);
            if (create == 1)
            {
                return RedirectToAction("Index");
            }
            else return View();
           }

        // Create Order by selecting product
       public ActionResult CreateProductOrder()
        {
            ViewBag.list = client.AddingToOrderDetails();
            return View(new Products());
        }

        [HttpPost]
        public ActionResult CreateProductOrder(Products orderDetails, int id, string str)
        {
            int create = client.postOrderDetails(orderDetails, id);
            if (create == 1)
            {
                return RedirectToAction("OrderDetails", new { id = str });
            }
            else return View();

        } 

        // Edit Customer details
        public ActionResult Edit(string id)
        {
           Customer1 customer = new Customer1();
            customer = client.EditView(id);
            return View(customer);
        }

        [HttpPost]
        public ActionResult Edit(Customer1 customer)
        {            
           int save = client.Edit(customer);
            if (save == 1) {
                return RedirectToAction("Index");
            }
            else return View();
        }

        // View next customer's details
        public ActionResult Next(string id)
        {
            return View(client.Next(id));
        }

        // View first customer's detail
        public ActionResult First()
        {
            return View(client.First());
        }

        // Place Order in 'Orders' table
        public ActionResult placeOrder()
        {
            return View(new Order());
        }

        [HttpPost]
        public ActionResult placeOrder(Order order, string id)
        {
            client.OrderAgainstCustomer(order, id);
            return RedirectToAction("OrderDetails", new { id = id });
        }

        // Delete Customer 
        public ActionResult Delete(string id)
        {
            client.Delete(id);
            return RedirectToAction("Index");
        }


    }
}

MVCWFE/Views/Customer1/Create.cshtml
@model MVCWFE.ServiceReference1.Customer1

@{
    ViewBag.Title = "Create";
}

<h2> Add new Customer </h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer1</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.CustomerID, "Please Enter exactly 5 characters ID * ", new { @class = "text-danger" })
                @Html.EditorFor(model => model.CustomerID, new { htmlAttributes = new { @maxlength = "5", @minlength = "5" , @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVCWFE/Views/Customer1/CreateProduct.cshtml
@model Models.Products

@{
    ViewBag.Title = "CreateProduct";
}

<h2> Add Product </h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    
    <hr />
    <!--     @Html.ValidationSummary(true, "", new { @class = "text-danger" })
         <div class="form-group">
             @Html.LabelFor(model => model.ProductID, htmlAttributes: new { @class = "control-label col-md-2" })
             <div class="col-md-10">
                 @Html.EditorFor(model => model.ProductID, new { htmlAttributes = new { @class = "form-control" } })
                 @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
             </div>
         </div> -->

    <div class="form-group">
        @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SupplierID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SupplierID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CategoryID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QuantityPerUnit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QuantityPerUnit, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QuantityPerUnit, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UnitsInStock, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UnitsInStock, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UnitsInStock, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UnitsOnOrder, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UnitsOnOrder, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UnitsOnOrder, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ReorderLevel, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ReorderLevel, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ReorderLevel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Discontinued, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Discontinued)
                @Html.ValidationMessageFor(model => model.Discontinued, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVCWFE/Views/Customer1/CreateProductOrder.cshtml
@model MVCWFE.ServiceReference1.Products

@{
    ViewBag.Title = "CreateProductOrder";
}

<h2> Place Order </h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProductName, new SelectList(ViewBag.list), "select product ID", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVCWFE/Views/Customer1/Delete.cshtml
@model Models.Customer1

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer1</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCWFE/Views/Customer1/Details.cshtml
@model  IEnumerable<MVCWFE.ServiceReference1.Customer1>

@{
    ViewBag.Title = "Details";
}


<div>
    <h4>Customer Detail</h4>
    <hr />

    <table border="2" style="border-color: black" >
        <tr>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.CustomerID)   &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.CompanyName)  &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.ContactName)  &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.ContactTitle) &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.Address)      &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.City)         &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.Region)       &nbsp</th>
            <th></th>

        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>&nbsp @Html.DisplayFor(modelItem => item.CustomerID)   &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.CompanyName)  &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.ContactName)  &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.ContactTitle) &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.Address)      &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.City)         &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.Region)       &nbsp </td>
                <td>
                    &nbsp
                    @Html.ActionLink("Edit", "Edit", new { id = (item.CustomerID) }) &nbsp |

                    @Html.ActionLink("Orders", "OrderDetails", new { id = (item.CustomerID) }) |

                    @Html.ActionLink("Next", "Next", new { id = (item.CustomerID) }) &nbsp

                </td>

            </tr>

        }

    </table>
 
</div>

<div>
    <br />  <br />  <br /> 
    <button style="border-block-color:darkcyan ">  @Html.ActionLink("Back to List", "Index") </button>

    <button style="border-block-color:darkcyan ">
        @Html.ActionLink("First", "First")
    </button>
</div>

MVCWFE/Views/Customer1/First.cshtml
@model IEnumerable<MVCWFE.ServiceReference1.Customer1>

@{
    ViewBag.Title = "First";
}

<div>
    <h4>Customer Detail</h4>
    <hr />

    <table border="2" style="border-color: black">
        <tr>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.CustomerID)   &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.CompanyName)  &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.ContactName)  &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.ContactTitle) &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.Address)      &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.City)         &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.Region)       &nbsp</th>
            <th></th>

        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>&nbsp @Html.DisplayFor(modelItem => item.CustomerID)   &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.CompanyName)  &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.ContactName)  &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.ContactTitle) &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.Address)      &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.City)         &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.Region)       &nbsp </td>
                <td>
                    &nbsp
                    @Html.ActionLink("Edit", "Edit", new { id = (item.CustomerID) }) &nbsp |

                    @Html.ActionLink("Orders", "OrderDetails", new { id = (item.CustomerID) }) |

                    @Html.ActionLink("Next", "Next", new { id = (item.CustomerID) }) &nbsp

                </td>

            </tr>

        }

    </table>

</div>

<div>
    <br />  <br />  <br />
    <button style="border-block-color:darkcyan ">  @Html.ActionLink("Back to List", "Index") </button>

    <button style="border-block-color:darkcyan ">
        @Html.ActionLink("First", "First")
    </button>
</div>

MVCWFE/Views/Customer1/Index.cshtml
@model IEnumerable<MVCWFE.ServiceReference1.Customer1>

@{
    ViewBag.Title = "AllCustomers";
}

<h2> Customers List </h2>

<button style="border-block-color:darkcyan ; color: white">
    @Html.ActionLink("Add Customer", "Create")
</button>

<br /><br />

<table border="3" style="border-color: black">
    <tr style="border-block-color: black">
        <th>
            &nbsp
            @Html.DisplayNameFor(model => model.CustomerID)
        </th>
        <th>
            &nbsp
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            &nbsp
            @Html.DisplayNameFor(model => model.ContactName)
        </th>
        <!--
        <th>
            @Html.DisplayNameFor(model => model.ContactTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Region)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostalCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fax)
        </th> -->
    <th>&nbsp Operations </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                &nbsp
                @Html.DisplayFor(modelItem => item.CustomerID)
            </td>
            <td>
                &nbsp
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                &nbsp
                @Html.DisplayFor(modelItem => item.ContactName)
            </td>
            <!--
            <td>
                @Html.DisplayFor(modelItem => item.ContactTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostalCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fax)
            </td>
                -->
        <td style="color: darkslategrey" >
            &nbsp
            @Html.ActionLink("Edit", "Edit", new { id = (item.CustomerID) })&nbsp |&nbsp
            @Html.ActionLink("Details", "Details", "Customer1", new { id = (item.CustomerID) }, null) &nbsp|&nbsp
            @Html.ActionLink("Delete", "Delete", new { id = (item.CustomerID) }, null)&nbsp&nbsp
        </td>
        </tr>
    }

</table>

MVCWFE/Views/Customer1/Next.cshtml
@model IEnumerable<MVCWFE.ServiceReference1.Customer1>

@{
    ViewBag.Title = "Details";
}

<div>
    <h4>Customer Detail</h4>
    <hr />

    <table border="2" style="border-color: black">
        <tr>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.CustomerID)   &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.CompanyName)  &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.ContactName)  &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.ContactTitle) &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.Address)      &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.City)         &nbsp</th>
            <th>&nbsp&nbsp   @Html.DisplayNameFor(model => model.Region)       &nbsp</th>
            <th></th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>&nbsp @Html.DisplayFor(modelItem => item.CustomerID)   &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.CompanyName)  &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.ContactName)  &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.ContactTitle) &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.Address)      &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.City)         &nbsp </td>
                <td>&nbsp @Html.DisplayFor(modelItem => item.Region)       &nbsp </td>
                <td>
                    &nbsp
                    @Html.ActionLink("Edit", "Edit", new { id = (item.CustomerID) }) &nbsp |

                    @Html.ActionLink("Orders", "OrderDetails", new { id = (item.CustomerID) }) |

                    @Html.ActionLink("Next", "Next", new { id = (item.CustomerID) }) &nbsp

                </td>

            </tr>

        }

    </table>

</div>

<div>
    <br />  <br />  <br />
    <button style="border-block-color:darkcyan ">  @Html.ActionLink("Back to List", "Index") </button>

    <button style="border-block-color:darkcyan ">
        @Html.ActionLink("First", "First")
    </button>
</div>

MVCWFE/Views/Customer1/OrderDetails.cshtml
@model IEnumerable<MVCWFE.ServiceReference1.Order>


@{
    ViewBag.Title = "OrderDetails";
}

<h4>OrderDetails</h4>
<br />
<br />

<table border="2" style="border-color: black">
    <tr>
        <th>&nbsp @Html.DisplayNameFor(model => model.CustomerID)     &nbsp </th>
        <th>&nbsp @Html.DisplayNameFor(model => model.OrderID)        &nbsp </th>
        <th>&nbsp @Html.DisplayNameFor(model => model.ShipName)       &nbsp </th>
        <th>&nbsp @Html.DisplayNameFor(model => model.ShipAddress)    &nbsp </th>
        <th>&nbsp @Html.DisplayNameFor(model => model.ShipCity)       &nbsp  </th>
        <th>&nbsp @Html.DisplayNameFor(model => model.ShipRegion)     &nbsp  </th>
        <th>&nbsp @Html.DisplayNameFor(model => model.ShipPostalCode) &nbsp  </th>
        <th>&nbsp @Html.DisplayNameFor(model => model.ShipCountry)    &nbsp  </th>
        <th>&nbsp Operations &nbsp</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>&nbsp @Html.DisplayFor(modelItem => item.CustomerID) &nbsp  </td>
            <td>&nbsp @Html.DisplayFor(modelItem => item.OrderID) &nbsp  </td>
            <td>&nbsp @Html.DisplayFor(modelItem => item.ShipName) &nbsp </td>
            <td>&nbsp @Html.DisplayFor(modelItem => item.ShipAddress) &nbsp </td>
            <td>&nbsp @Html.DisplayFor(modelItem => item.ShipCity)&nbsp </td>
            <td>&nbsp @Html.DisplayFor(modelItem => item.ShipRegion)  &nbsp    </td>
            <td>&nbsp @Html.DisplayFor(modelItem => item.ShipPostalCode) &nbsp        </td>
            <td>&nbsp @Html.DisplayFor(modelItem => item.ShipCountry)    &nbsp   </td>
            <td>
                &nbsp

                @Html.ActionLink("Back", "Details", "Customer1", new { id = (item.CustomerID) }, null) &nbsp | &nbsp
                @Html.ActionLink("New OrderID", "placeOrder", "Customer1", new { id = (item.CustomerID) }, null) &nbsp | &nbsp
                @Html.ActionLink("Place Order", "CreateProductOrder", "Customer1", new { id = (item.OrderID), str = (item.CustomerID) }, null) &nbsp

            </td>

        </tr>
    }

</table>

<br />
<br />
<button> @Html.ActionLink("Back to List", "Index") </button>